apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
data:
  S3_REGION: "us-east-1"
  S3_BUCKET: "tolbargy-test-k8s"
  AWS_KEY: "AKIAY6HTXRLEBH35Q5RV"
  AWS_SECRET_KEY: "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"