version: '3'
services:
  mysql57:
    image: ofthesun9/mysql:5.7
    platform: linux/arm
    container_name: mysql57
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: raspberry
    volumes:
      - "/home/pi/workspace/volumes/mysql57-data:/var/lib/mysql"