# Use root/example as user/password credentials
version: '3.1'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tolbar12345
    ports:
      - 3306:3306
    volumes:
      - C:/volumes/mysql8:/var/lib/mysql