apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: www-volume

  volumes:
  - name: www-volume
    hostPath:
      path: /run/desktop/mnt/host/c/volumes-kubernetes/test-nginx
      type: DirectoryOrCreate