apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 3
  selector:
    matchLabels:
      role: nginx-example
  template:
    metadata:
      labels:
        role: nginx-example
    spec:
      containers:
      - name: example-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80